### ISSUE TITLE
Velocity in simulation

### ISSUE THREAD

**Issue by lixuekai2001** [ovcharenkoo/WaveProp_in_MATLAB#4]
I quote the 2D acoustic simulation that within 0.5282 seconds the wavefront has moved about 150 m from the source. It means that the velocity is about 283 m/s, which is very different from the given vp = 3300.0 m/s. 
This issue happens for all examples.

**Comment by ovcharenkoo** [comment]
Hi @lixuekai2001, good catch, thank you. The reason appears to be in incorrect axes labeling. The plotting routine simply plots the matrix where the limits over X and Y correspond to the matrix size. 

Try the following to get the proper axes ticks in meters 
```matlab
% Before the time loop
x_ticks = linspace(1, (nx - 1) * dx, nx)
z_ticks = linspace(1, (nz - 1) * dz, nz)
...
% In the plotting part
imagesc(x_ticks, z_ticks, p3); colorbar; 
axis equal tight; colormap jet; xlabel('m'); ylabel('m');
```

Currently, I don't have Matlab on my machine but the solution should be similar to the above

**Comment by ovcharenkoo** [comment]
Hope this solved the issue
