### ISSUE TITLE
boundary condition is not good enough

### ISSUE THREAD

**Issue by jj21770** [ovcharenkoo/WaveProp_in_MATLAB#5]
I have try this code by 200x300 grid with dx=10 dz=20, I found it have a really heavy reflec wave. I have tried to adjust the abs_rate and dt parameters, but it still bad.

**Comment by ovcharenkoo** [comment]
Hi @jj21770 implementation of good absorbing boundary conditions such as PML is not a trivial task, for the sake of simplicity, we use simple boundaries here. 

For example of PML implementation in Matlab have a look [here](https://www.mathworks.com/matlabcentral/fileexchange/77521-perfectly-matched-layer-for-a-standard-wave-equation)
